require "rdiscount"
require "mustache"
require "active_support/core_ext/string"
require "fileutils"
require "yaml"
load File.dirname(__FILE__) + "/site/index-ja.rb"

def generate(page, template = "site/page.ms")
  Mustache.render(
    File.read(template), 
    page.merge(:content => RDiscount.new(File.read(page[:src])).to_html),
  )
end

task :generate do
  pages = Dir["chapters/*.md"].inject([]) do |array, src|
    array << ({
      :src    => src,
      :static => File.basename(src, ".md") + ".html",
      :name   => if defined? $chapters then $chapters[File.basename(src, ".md")] else File.basename(src, ".md").gsub(/\d+_/, "").titleize end,
      :href   => File.basename(src, ".md") + ".html"
    })
    array
  end
  
  pages.each do |page|
    File.open(page[:static], "w+") do |f|
      f.write generate(page)
    end
  end
  
  File.open("index.html", "w+") do |f|
    f.write(Mustache.render(
      File.read("site/index.ms"), 
      :pages => pages
    ))
  end  
end

task :default => :generate
